"""empty message

Revision ID: 6aa1d52d6712
Revises: 
Create Date: 2021-09-06 19:54:08.798690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aa1d52d6712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date', sa.DateTime(), nullable=False))
    op.drop_column('movie', 'releaseDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('releaseDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###
